// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFo_8MvcSEPodtqtIXMHt6o8uOtBj3bV0',
    appId: '1:720143189830:web:04a0d136fafcc2a7c5c747',
    messagingSenderId: '720143189830',
    projectId: 'rdp-todo-list-55101',
    authDomain: 'rdp-todo-list-55101.firebaseapp.com',
    storageBucket: 'rdp-todo-list-55101.firebasestorage.app',
    measurementId: 'G-Q7XG5R2EPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfBPRay2A7hwxevo0q9a0d5BuUkqKeiag',
    appId: '1:720143189830:android:c3b3fe59026e55e0c5c747',
    messagingSenderId: '720143189830',
    projectId: 'rdp-todo-list-55101',
    storageBucket: 'rdp-todo-list-55101.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFo_8MvcSEPodtqtIXMHt6o8uOtBj3bV0',
    appId: '1:720143189830:web:22412bb35d50d4a0c5c747',
    messagingSenderId: '720143189830',
    projectId: 'rdp-todo-list-55101',
    authDomain: 'rdp-todo-list-55101.firebaseapp.com',
    storageBucket: 'rdp-todo-list-55101.firebasestorage.app',
    measurementId: 'G-K1WHHQMJH8',
  );

}